version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #è®¾ç½®rootå¸å·å¯†ç 
    ports:
      - 3306:3306
    volumes:
      - /mydata/mysql/data/db:/var/lib/mysql #æ•°æ®æ–‡ä»¶æŒ‚è½½
      - /mydata/mysql/data/conf:/etc/mysql/conf.d #é…ç½®æ–‡ä»¶æŒ‚è½½
      - /mydata/mysql/log:/var/log/mysql #æ—¥å¿—æ–‡ä»¶æŒ‚è½½
  redis:
    image: redis:5
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - /mydata/redis/data:/data #æ•°æ®æ–‡ä»¶æŒ‚è½½
    ports:
      - 6379:6379
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - /mydata/nginx/conf:/etc/nginx #é…ç½®æ–‡ä»¶æŒ‚è½½
      - /mydata/nginx/html:/usr/share/nginx/html #é™æ€èµ„æºæ ¹ç›®å½•æŒ‚è½½
      - /mydata/nginx/log:/var/log/nginx #æ—¥å¿—æ–‡ä»¶æŒ‚è½½
    ports:
      - 80:80
      - 443:443
  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    volumes:
      - /mydata/rabbitmq/data:/var/lib/rabbitmq #æ•°æ®æ–‡ä»¶æŒ‚è½½
      - /mydata/rabbitmq/log:/var/log/rabbitmq #æ—¥å¿—æ–‡ä»¶æŒ‚è½½
    ports:
      - 5672:5672
      - 15672:15672
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    user: root
    environment:
      - "cluster.name=elasticsearch" #è®¾ç½®é›†ç¾¤åç§°ä¸ºelasticsearch
      - "discovery.type=single-node" #ä»¥å•ä¸€èŠ‚ç‚¹æ¨¡å¼å¯åŠ¨
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #è®¾ç½®ä½¿ç”¨jvmå†…å­˜å¤§å°
    volumes:
      - /mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins #æ’ä»¶æ–‡ä»¶æŒ‚è½½
      - /mydata/elasticsearch/data:/usr/share/elasticsearch/data #æ•°æ®æ–‡ä»¶æŒ‚è½½
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    image: logstash:7.6.2
    container_name: logstash
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mydata/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #æŒ‚è½½logstashçš„é…ç½®æ–‡ä»?
    depends_on:
      - elasticsearch #kibanaåœ¨elasticsearchå¯åŠ¨ä¹‹åå†å¯åŠ?
    links:
      - elasticsearch:es #å¯ä»¥ç”¨esè¿™ä¸ªåŸŸåè®¿é—®elasticsearchæœåŠ¡
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
  kibana:
    image: kibana:7.6.2
    container_name: kibana
    links:
      - elasticsearch:es #å¯ä»¥ç”¨esè¿™ä¸ªåŸŸåè®¿é—®elasticsearchæœåŠ¡
    depends_on:
      - elasticsearch #kibanaåœ¨elasticsearchå¯åŠ¨ä¹‹åå†å¯åŠ?
    environment:
      - "elasticsearch.hosts=http://es:9200" #è®¾ç½®è®¿é—®elasticsearchçš„åœ°å€
    ports:
      - 5601:5601
  mongo:
    image: mongo:4.2.5
    container_name: mongo
    volumes:
      - /mydata/mongo/db:/data/db #æ•°æ®æ–‡ä»¶æŒ‚è½½
    ports:
      - 27017:27017
  nacos-registry:
    image: nacos/nacos-server:latest
    container_name: nacos-registry
    environment:
      - "MODE=standalone"
    ports:
      - 8848:8848
